# permissions for end users to view k8scrcheckpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k8scrcheckpoint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-container-checkpoint
    app.kubernetes.io/part-of: kubernetes-container-checkpoint
    app.kubernetes.io/managed-by: kustomize
  name: k8scrcheckpoint-viewer-role
rules:
- apiGroups:
  - kangmingfa.go.kangmingfa.go
  resources:
  - k8scrcheckpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kangmingfa.go.kangmingfa.go
  resources:
  - k8scrcheckpoints/status
  verbs:
  - get
