---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kangmingfa.go.kangmingfa.go
  resources:
  - k8scrcheckpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kangmingfa.go.kangmingfa.go
  resources:
  - k8scrcheckpoints/finalizers
  verbs:
  - update
- apiGroups:
  - kangmingfa.go.kangmingfa.go
  resources:
  - k8scrcheckpoints/status
  verbs:
  - get
  - patch
  - update
